# Generated by Django 4.1.7 on 2023-03-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_column_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Column name'),
        ),
    ]
