# Generated by Django 4.1.7 on 2023-03-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filename',
            name='status',
            field=models.CharField(default='Processing', max_length=50),
        ),
    ]
