# Generated by Django 4.1.7 on 2023-03-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_filename_schema_id_alter_filename_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filename',
            name='download_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
