# Generated by Django 4.1.7 on 2023-03-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_filename_download_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileName',
        ),
    ]
