# Generated by Django 4.1.7 on 2023-03-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filename',
            name='file',
        ),
    ]
